#################################### common config : ####################################
spring:
  application:
    name: zipkin-server
  profiles:
    active: dev
# 应用服务web访问端口
server:
  port: 9411


