
eureka:
  client:
    service-url:
      #      defaultZone: http://api:node@node2:8762/eureka/,http://api:node@node1:8761/eureka/
      defaultZone: http://api:node@localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}:@project.name@
    prefer-ip-address: true
    ip-address: 127.0.0.1

