server:
  port: 8761
spring:
  security:
    user:
      name: api
      password: node
      roles: SERVICE_ROLE
eureka:
  client:
    service-url:
      defaultZone: http://api:node@${eureka.instance.hostname}:${server.port}/eureka/
    fetch-registry: false #是否同步其他服务中心的列表
    register-with-eureka: false #是否把自己注册到其他服务中
  instance:
    hostname: localhost
#    instance-id: ${eureka.instance.hostname}:${server.port}:@project.version@
  server:
    peer-node-read-timeout-ms: 1000